-- Memoria estructurada de LC Performance.
-- Ejecutar una sola vez en Supabase SQL Editor con un usuario propietario.

create extension if not exists pgcrypto;

-- Tablas legacy que el bot ya utiliza para archivo de mensajes y perfil liviano.
create table if not exists public.lc_mensajes (
  id bigint generated by default as identity primary key,
  phone text not null,
  direction text not null,
  content text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.lc_clientes (
  phone text primary key,
  nombre text,
  vehiculos text,
  estilo text,
  resumen text,
  ultimo_servicio text,
  updated_at timestamptz not null default now()
);

create table if not exists public.lc_customers (
  id uuid primary key default gen_random_uuid(),
  contact_key text not null unique,
  channel text not null default 'whatsapp' check (channel in ('whatsapp', 'instagram', 'other')),
  display_name text,
  communication_style text,
  customer_safe_summary text,
  do_not_contact boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lc_vehicles (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.lc_customers(id) on delete cascade,
  label text not null,
  make text,
  model text,
  model_year integer,
  plate text,
  current_mileage integer,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (customer_id, label)
);

create table if not exists public.lc_service_records (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.lc_customers(id) on delete cascade,
  vehicle_id uuid references public.lc_vehicles(id) on delete set null,
  local_appointment_id integer,
  service_date date not null default current_date,
  work_performed text not null,
  vehicle_condition text,
  mileage integer,
  unresolved_items text,
  recorded_by text not null default 'lucas',
  visibility text not null default 'internal_only' check (visibility in ('internal_only', 'customer_safe')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.lc_internal_notes (
  id uuid primary key default gen_random_uuid(),
  customer_id uuid not null references public.lc_customers(id) on delete cascade,
  vehicle_id uuid references public.lc_vehicles(id) on delete set null,
  note text not null,
  category text not null default 'general',
  created_by text not null default 'lucas',
  created_at timestamptz not null default now()
);

create table if not exists public.lc_followup_sequences (
  id uuid primary key default gen_random_uuid(),
  contact_key text not null,
  recipient_address text not null,
  channel text not null default 'whatsapp' check (channel in ('whatsapp', 'instagram')),
  trigger_message_id text,
  trigger_kind text not null default 'conversation',
  status text not null default 'pending' check (status in ('pending', 'processing', 'cancelled', 'completed', 'exhausted')),
  attempt_count smallint not null default 0 check (attempt_count between 0 and 2),
  send_failure_count smallint not null default 0 check (send_failure_count between 0 and 3),
  next_run_at timestamptz not null,
  last_attempt_at timestamptz,
  locked_at timestamptz,
  cancel_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists lc_followup_one_active_per_contact
  on public.lc_followup_sequences(contact_key, channel)
  where status in ('pending', 'processing');

create index if not exists lc_followup_due_idx
  on public.lc_followup_sequences(status, next_run_at);

create index if not exists lc_service_customer_date_idx
  on public.lc_service_records(customer_id, service_date desc);

create or replace function public.lc_claim_due_followups(p_limit integer default 25)
returns setof public.lc_followup_sequences
language plpgsql
security definer
set search_path = public
as $$
begin
  -- Si una instancia murió después de reclamar filas, se vuelven a habilitar.
  update public.lc_followup_sequences
     set status = 'pending', locked_at = null, updated_at = now()
   where status = 'processing'
     and locked_at < now() - interval '15 minutes';

  return query
  with candidates as (
    select id
    from public.lc_followup_sequences
    where status = 'pending'
      and next_run_at <= now()
    order by next_run_at
    for update skip locked
    limit greatest(1, least(p_limit, 100))
  )
  update public.lc_followup_sequences f
     set status = 'processing', locked_at = now(), updated_at = now()
    from candidates c
   where f.id = c.id
  returning f.*;
end;
$$;

revoke all on function public.lc_claim_due_followups(integer) from public;
revoke all on function public.lc_claim_due_followups(integer) from anon;
revoke all on function public.lc_claim_due_followups(integer) from authenticated;
grant execute on function public.lc_claim_due_followups(integer) to service_role;

alter table public.lc_customers enable row level security;
alter table public.lc_vehicles enable row level security;
alter table public.lc_service_records enable row level security;
alter table public.lc_internal_notes enable row level security;
alter table public.lc_followup_sequences enable row level security;
alter table public.lc_mensajes enable row level security;
alter table public.lc_clientes enable row level security;

-- No se crean policies públicas: estas tablas se usan exclusivamente desde el
-- servidor con SUPABASE_SECRET_KEY (service role).
